resolver: lts-12.0
packages:
- '.'
extra-deps:
  - streamly-0.4.0
  - drinkery-0.3

  # for lts-12.0
  - bench-graph-0.1.1
  - Chart-1.9
  - Chart-diagrams-1.9
  - SVGFonts-1.6.0.3

rebuild-ghc-options: true
